name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    name: Disabled
    steps:
      - name: Workflow disabled
        run: echo "Static Web Apps deployment workflow disabled by configuration."
